on:
    workflow_dispatch:

jobs:
    get:
      runs-on: ubuntu-latest
      steps:
         - name: Get Github App Token
           uses: actions/create-github-app-token@v1
           id: generate-token
           with:
             app-id: ${{ secrets.APP_ID }}
             private-key: ${{ secrets.APP_PEM }}

         - name: Check API
           env:
            GH_TOKEN: ${{ steps.generate-token.outputs.token }}
           run: |
               gh api /app
