on:
    workflow_dispatch:

jobs:
    get:
      runs-on: ubuntu-latest
      steps:
         - name: Get Github App Token
           uses: actions/create-github-app-token@v1
           id: generate-token
           with:
             app-id: ${{ secrets.APP_ID }}
             private-key: ${{ secrets.APP_PEM }}

         - name: Test API
           uses: actions/github-script@v7
           with:
               script: |
                 import { App } from "octokit"
                 async function main() {
                   const app = new App({
                      appId: ${{ secrets.APP_ID }},
                      privateKey: ${{ secrets.APP_PEM }}
                   });
                   console.log(await app.octokit.request("/app"));
                 };
                 main();
                
             
#         - name: Check API
#           env:
#            GH_TOKEN: ${{ steps.generate-token.outputs.token }}
#           run: |
 #              gh api /app/installations
 #              gh api /app
